// <auto-generated />
using System;
using FeedNews.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FeedNews.Infrastructure.Migrations
{
    [DbContext(typeof(FeedNewsContext))]
    partial class FeedNewsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeedNews.Domain.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("avatar_url");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text")
                        .HasColumnName("device_token");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<int>("NumOfFlag")
                        .HasColumnType("integer")
                        .HasColumnName("num_of_flag");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_account_role_id");

                    b.HasIndex(new[] { "Email" }, "account_email_unique")
                        .IsUnique()
                        .HasDatabaseName("ix_account_email");

                    b.HasIndex(new[] { "PhoneNumber" }, "account_phone_number_unique")
                        .IsUnique()
                        .HasDatabaseName("ix_account_phone_number");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Attribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_attribute");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_attribute_game_id");

                    b.ToTable("attribute", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_customer_wallet_id");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Favourite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<long>("GAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("g_account_id");

                    b.HasKey("Id")
                        .HasName("pk_favourite");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_favourite_customer_id");

                    b.HasIndex("GAccountId")
                        .HasDatabaseName("ix_favourite_g_account_id");

                    b.ToTable("favourite", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.GAccountAttribute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("GAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("g_account_id");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.HasKey("Id")
                        .HasName("pk_gaccount_attribute");

                    b.HasIndex("AttributeId")
                        .HasDatabaseName("ix_gaccount_attribute_attribute_id");

                    b.HasIndex("GAccountId")
                        .HasDatabaseName("ix_gaccount_attribute_g_account_id");

                    b.ToTable("gaccount_attribute", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_game");

                    b.ToTable("game", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.GameAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AttributesJson")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("attributes_json");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint")
                        .HasColumnName("game_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("price");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_game_account");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_game_account_game_id");

                    b.ToTable("game_account", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_date");

                    b.Property<decimal>("RankingScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ranking_score");

                    b.Property<DateTime?>("SlackSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("slack_sent_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.Property<string>("Summary")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news_feeds_id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("uq_news_feeds_url");

                    b.HasIndex("Category", "PublishedDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_news_feeds_category_pubdate");

                    b.HasIndex("FetchedAt", "SlackSentAt")
                        .HasDatabaseName("idx_news_feeds_fetched_slack");

                    b.ToTable("news_feeds", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_notification_account_id");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("complete_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<long>("GAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("g_account_id");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("boolean")
                        .HasColumnName("is_refund");

                    b.Property<bool>("IsReport")
                        .HasColumnType("boolean")
                        .HasColumnName("is_report");

                    b.Property<DateTimeOffset>("OrderAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_at");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("price");

                    b.Property<decimal>("Promotion")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("promotion");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_order_customer_id");

                    b.HasIndex("GAccountId")
                        .HasDatabaseName("ix_order_g_account_id");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("amount");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("Status")
                        .HasColumnType("bigint")
                        .HasColumnName("status");

                    b.Property<string>("TransactionContent")
                        .HasColumnType("text")
                        .HasColumnName("transaction_content");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("transaction_id");

                    b.Property<long>("Type")
                        .HasColumnType("bigint")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_payment");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payment_order_id");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnnounceMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("announce_message");

                    b.Property<string>("PopupMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("popup_message");

                    b.HasKey("Id")
                        .HasName("pk_system_config");

                    b.ToTable("system_config", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Wallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AvailableAmount")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("available_amount");

                    b.Property<decimal>("IncomingAmount")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("incoming_amount");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wallet");

                    b.ToTable("wallet", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("AvailableAmountBefore")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("available_amount_before");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("IncomingAmountBefore")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("incoming_amount_before");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_transaction");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_wallet_transaction_wallet_id");

                    b.ToTable("wallet_transaction", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.WithdrawRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("BankAccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_account_name");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_code");

                    b.Property<string>("BankShortName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_short_name");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<long>("WalletId")
                        .HasColumnType("bigint")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_withdraw_request");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_withdraw_request_wallet_id");

                    b.ToTable("withdraw_request", (string)null);
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Account", b =>
                {
                    b.HasOne("FeedNews.Domain.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Attribute", b =>
                {
                    b.HasOne("FeedNews.Domain.Entities.Game", "Game")
                        .WithMany("Attributes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attribute_game");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Customer", b =>
                {
                    b.HasOne("FeedNews.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Customers")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_wallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Favourite", b =>
                {
                    b.HasOne("FeedNews.Domain.Entities.Account", "Customer")
                        .WithMany("Favourites")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favourite_customer");

                    b.HasOne("FeedNews.Domain.Entities.GameAccount", "GameAccount")
                        .WithMany("Favourites")
                        .HasForeignKey("GAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favourite_gameaccount");

                    b.Navigation("Customer");

                    b.Navigation("GameAccount");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.GAccountAttribute", b =>
                {
                    b.HasOne("FeedNews.Domain.Entities.Attribute", "Attribute")
                        .WithMany("GAccountAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gaccountattribute_attribute");

                    b.HasOne("FeedNews.Domain.Entities.GameAccount", "GameAccount")
                        .WithMany("GAccountAttributes")
                        .HasForeignKey("GAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gaccountattribute_gameaccount");

                    b.Navigation("Attribute");

                    b.Navigation("GameAccount");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.GameAccount", b =>
                {
                    b.HasOne("FeedNews.Domain.Entities.Game", "Game")
                        .WithMany("GameAccounts")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gameaccount_game");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FeedNews.Domain.Entities.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Order", b =>
                {
                    b.HasOne("FeedNews.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_customer");

                    b.HasOne("FeedNews.Domain.Entities.GameAccount", "GameAccount")
                        .WithMany("Orders")
                        .HasForeignKey("GAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_gameaccount");

                    b.Navigation("Customer");

                    b.Navigation("GameAccount");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Payment", b =>
                {
                    b.HasOne("FeedNews.Domain.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("FeedNews.Domain.Entities.Wallet", "Wallet")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallettransaction_wallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.WithdrawRequest", b =>
                {
                    b.HasOne("FeedNews.Domain.Entities.Wallet", "Wallet")
                        .WithMany("WithdrawRequests")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_withdrawrequest_wallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Account", b =>
                {
                    b.Navigation("Favourites");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Attribute", b =>
                {
                    b.Navigation("GAccountAttributes");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Game", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("GameAccounts");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.GameAccount", b =>
                {
                    b.Navigation("Favourites");

                    b.Navigation("GAccountAttributes");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Order", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("FeedNews.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("WalletTransactions");

                    b.Navigation("WithdrawRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
